port: 8080
logger: info
sql:
  connection: ./sql/Dpanel.db
  driver: sqlite
  MAX_OPEN_CONS: 100
  MAX_IDLE_CONS: 20
  MAX_LIFE_TIME: 100
#sql:
#  connection: dpanel:s4GEGRX6wXzw7zEK@(10.0.0.4:3306)/dpanel?charset=utf8mb4&parseTime=True&loc=Local
#  driver: mysql
#  MAX_OPEN_CONS: 100
#  MAX_IDLE_CONS: 20
#  MAX_LIFE_TIME: 100
jwt:
  secret: 0ee2662765b978639f503d90e95f8fa7
redis:
  host: 10.0.0.4
  port: 6379
  password: jhkdjhkjdhsIUTYURTU_pC7rWC
  db: 2